
# recompile libaries used by the rust compiler as our operating system 
# is free from that when initializing
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# use the json configurations
[build]
target = "src/x86_64-carrot_os.json"

[target.x86_64-carrot_os]
rustflags = [
	"-C", "relocation-model=static",
	"-C", "link-arg=-Tlinker.ld",
	"-C", "code-model=kernel",
	# "-C", "link-arg=-Ttext=0xffffffff80000000"
]

[run]
target = "src/x86_64-carrot_os.json"

# make this a standalone operating system
[target.'cfg(target_os = "none")']
runner = "bootimage runner" # use bootimage as our bootloader
