
# recompile libaries used by the rust compiler as our operating system 
# is free from that when initializing
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# use the json configurations
[build]
target = "x86_64_carrot_os.json"

[run]
target = "x86_64_carrot_os.json"

# make this a standalone operating system
[target.'cfg(target_os = "none")']
runner = "bootimage runner" # use bootimage as our bootloader
